batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507272245
train_epochs: 1000
train_workers: 20
vocab: LHDn:#.KWACc?GxjRieSdB+o,X-zvw!&rt(1)7Eh'"64u/V;0ZM3sUNQYqTl9gpfaI8kyJOb5F*P2m
width: 128
