batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507272233
train_epochs: 1000
train_workers: 20
vocab: 7,lA6h#dPE.j-o!1?s&C/+DbGqMr"nw43zVk*:WKfv'm8pJHe);TxNYcQ(XtBFISOagUZ5L0y9Riu2
width: 128
