batch_size: 8
height: 32
learning_rate: 0.001
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507280447
train_epochs: 5
train_workers: 2
vocab: ',0VJT+#"uQ1Yfcrj98Z;:*/pF-gGv!oEmRnd3(hMqK?C''bSzI)4HXBOPya5U6Ae2xtlikWws&NLD7.'
width: 128
