batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507272320
train_epochs: 10
train_workers: 20
vocab: BCXQ2POxeTaLknV8Wmo9q3#(/I5:jlsSK)tYrzvHJ&iA6?Md1RycbFh'G7gZ.D0;u"4p!-+fw,EUN*
width: 128
