batch_size: 32
height: 32
learning_rate: 0.001
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507272323
train_epochs: 5
train_workers: 20
vocab: YM',)l#f:SNR?Z8ATbJP9*240p+GCU.ira"Qh5edzIo3KXwHWcqOs(/-;gmLtkx67Vn!uFjyBD&v1E
width: 128
