batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507272242
train_epochs: 1000
train_workers: 20
vocab: vL3)?X"6bR!&wW5UZ1Fo*i'K+-7AV0#hGdIzf4PcDC8.TMaY;uQm/E(qtpgHksy:nJ2rSlxO9NjBe,
width: 128
