batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507280500
train_epochs: 5
train_workers: 20
vocab: E8ZQbU&?IG-(S1)DX:goW50rTjBhYLs,lJ;94HMfpN!6qenxav"t7AOCuKRFmV/#iyz.dkc+2*'wP3
width: 128
