batch_size: 16
height: 32
learning_rate: 0.001
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507280439
train_epochs: 5
train_workers: 20
vocab: 'rvU1.YCKH7c;"FlyEJ0PSIpuLb4Q)TMkone?m9!''q/8ax62+dGVwX*tONijhRDAZs3BzW&,g5f(#-:'
width: 128
