batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202507272250
train_epochs: 10
train_workers: 20
vocab: '#hwGHve)FrxT0gW7nAVj1S+b6REpQy3u(q4:o;s-/YO5PIa?''tkJ9DmfL."zNd!MiKBXl,&Uc*ZC82'
width: 128
